# Generated by Django 4.2.11 on 2024-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KatMateri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=20)),
                ('nm_kecil', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kat_materi',
            },
        ),
    ]
