# Generated by Django 4.2.11 on 2024-04-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katmateri',
            options={'verbose_name_plural': 'Kategori Materi'},
        ),
    ]
