# Generated by Django 4.2.11 on 2024-04-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_katmateri_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='katmateri',
            table=None,
        ),
    ]
