# Generated by Django 4.2.11 on 2024-04-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_katmateri_kode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katmateri',
            name='nm_kecil',
        ),
    ]
