# Generated by Django 4.2.11 on 2024-04-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_katmateri_nm_kecil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katmateri',
            options={'ordering': ['id'], 'verbose_name_plural': 'Kategori Materi'},
        ),
    ]
