# Generated by Django 4.2.11 on 2024-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_pengguna_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
