# Generated by Django 4.2.11 on 2024-04-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_pengguna_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengguna',
            old_name='password',
            new_name='passwd',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='username',
            new_name='uname',
        ),
    ]
