# Generated by Django 4.2.11 on 2024-04-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_rename_password_pengguna_passwd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengguna',
            old_name='passwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='uname',
            new_name='username',
        ),
    ]
