# Generated by Django 4.2.11 on 2024-04-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_delete_pengguna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.matakuliah')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.katmateri')),
            ],
            options={
                'verbose_name_plural': 'Posting',
                'ordering': ['id'],
            },
        ),
    ]
