# Generated by Django 4.2.5 on 2024-06-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_post_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
