# Generated by Django 4.2.5 on 2024-06-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_alter_post_gambar_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
    ]
