# Generated by Django 4.2.5 on 2024-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gambar',
        ),
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
