# Generated by Django 4.2.5 on 2024-07-02 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_proyek'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
