# Generated by Django 4.2.5 on 2024-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_proyek_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='status',
            field=models.CharField(choices=[('diterima', 'Diterima'), ('direview', 'Direview'), ('ditolak', 'Ditolak')], max_length=10),
        ),
    ]
