# Generated by Django 4.2.5 on 2024-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_proyek_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampul', models.ImageField(upload_to='event_covers/')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
