# Generated by Django 4.2.5 on 2024-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LamarProyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cv/')),
            ],
            options={
                'verbose_name_plural': 'LamarProyek',
            },
        ),
    ]
