# Generated by Django 4.2.5 on 2024-07-04 20:15

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_lamarproyek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamarproyek',
            name='cv',
            field=models.FileField(upload_to='cv/', validators=[forum.models.validate_file_extension]),
        ),
    ]
