# Generated by Django 4.2.5 on 2024-07-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_alter_lamarproyek_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamarproyek',
            name='kategori',
            field=models.CharField(blank=True, choices=[('lomba', 'Lomba'), ('pengabdian', 'Pengabdian'), ('individu', 'Individu')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lamarproyek',
            name='nama_proyek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.proyek'),
        ),
        migrations.AddField(
            model_name='lamarproyek',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('direview', 'Direview'), ('diterima', 'Diterima')], default='menunggu', max_length=10),
        ),
    ]
